version: '3.8'

services:
  main_service:
    build:
      context: ./backend/mainService
      dockerfile: Dockerfile
    ports:
      - "9020:8000"
    env_file:
      - ./backend/mainService/.env
    environment:
      - CREDIBILITY_API_URL=http://metrics_service:8000/api/v1/credibility/batch
    volumes:
      - ./backend/mainService:/app
    networks:
      - cite_me
    depends_on:
      - metrics_service

  metrics_service:
    build:
      context: ./backend/metricsService
      dockerfile: Dockerfile
    ports:
      - "9050:8000"
    env_file:
      - ./backend/metricsService/.env
    volumes:
      - ./backend/metricsService:/app
    networks:
      - cite_me

networks:
  cite_me:
    driver: bridge 